version: '3'
services:
  selenoid:
    container_name: selenoid
    image: "aerokube/selenoid:latest-release"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/output/video:/opt/selenoid/video"
      - "$PWD/output/logs:/opt/selenoid/logs"
    environment: 
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/output/video

  selenoid-ui:
    container_name: selenoid-ui
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "3030:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  
  selenoid-video-recorder:
    container_name: selenoid-video-recorder
    image: "selenoid/video-recorder:latest-release"